desc "create demoCA and register client(testuser)"
task :setupCA do
  sh <<-EOS
    set -Ceux
    sh scripts/ca.sh
    sh scripts/create_cert.sh testuser
  EOS
end

desc "start api mock server"
task :start do
  sh <<-EOS
    set -Ceux

    docker stop ssl-test || :
    docker rm ssl-test || :
    docker rmi ssl-test || :
    docker build -t ssl-test server

    docker run -p 8443:443 -p 8080:80 --rm --name ssl-test \
      -v $PWD/server/document_root/:/var/www/html \
      -v $PWD/server/log:/var/log/apache2 \
      ssl-test
  EOS
end

desc "access to mock server(http/https)"
task :test do
  sh <<-EOS
    python scripts/access-test.py
  EOS
end
