// Code generated by github.com/izumin5210/gex. DO NOT EDIT.

// +build tools

package tools

// tool dependencies
import (
	_ "github.com/volatiletech/sqlboiler"
	_ "github.com/volatiletech/sqlboiler-sqlite3"
)

// If you want to use tools, please run the following command:
//  go generate ./tools.go
//
//go:generate go build -v -o=./bin/sqlboiler github.com/volatiletech/sqlboiler
//go:generate go build -v -o=./bin/sqlboiler-sqlite3 github.com/volatiletech/sqlboiler-sqlite3
