DROP TABLE IF EXISTS TARGET;

DROP TABLE IF EXISTS SOURCE;

CREATE TABLE IF NOT EXISTS TARGET (
  ID         UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
  NAME       VARCHAR,
  AGE        INTEGER,
  CONSTRAINT TARGET_UNIQUE UNIQUE(NAME)
);

INSERT INTO TARGET (NAME, AGE) VALUES
('AAAAA', 10),
('BBBBB', 11),
('CCCCC', 12)
;

SELECT * FROM TARGET;


CREATE TABLE IF NOT EXISTS SOURCE (
  ID         UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
  NAME       VARCHAR,
  AGE        INTEGER,
  CONSTRAINT SOURCE_UNIQUE UNIQUE(NAME)
);

INSERT INTO SOURCE (NAME, AGE) VALUES
('BBBBB', 12),
('CCCCC', 13),
('DDDDD', 14),
('EEEEE', 15)
;

SELECT * FROM SOURCE;


-- UPSERT
BEGIN;

INSERT INTO TARGET (NAME, AGE)
SELECT NAME, AGE FROM SOURCE
ON CONFLICT ON CONSTRAINT TARGET_UNIQUE
DO UPDATE SET AGE = EXCLUDED.AGE;
;

-- DELETE
DELETE FROM TARGET
WHERE NOT EXISTS (
  SELECT *
  FROM SOURCE
  WHERE TARGET.NAME = SOURCE.NAME
)
;

COMMIT;


SELECT * FROM TARGET;
