FROM golang:1.17 as build
WORKDIR /go/src/hello
COPY go.mod hello.go ./
RUN go build -o hello .

FROM gcr.io/distroless/base
COPY --from=build /go/src/hello /
CMD ["/hello"]

# vim: set ft=dockerfile :
